/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package müller;

import com.expression.parser.Parser;
import com.expression.parser.util.ParserResult;
import com.expression.parser.util.Point;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import org.knowm.xchart.BitmapEncoder;
import org.knowm.xchart.BitmapEncoder.BitmapFormat;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;
import org.knowm.xchart.XYSeries;
import org.knowm.xchart.style.Styler;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author ASUS
 */
public class müller_Meto extends javax.swing.JFrame {

    /**
     * Creates new form müller_Meto
     */
    //Plot2DPanel evalFunction = new Plot2DPanel();

    public müller_Meto() {

        this.setResizable(false);
        this.setBounds(200, 20, 1000, 350);
        //evalFunction.setBounds(500, 100, 390, 300);
        //this.add(evalFunction);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextx2 = new javax.swing.JTextField();
        jTextx3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jText3 = new javax.swing.JTextField();
        jprincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JFUNCION = new javax.swing.JLabel();
        jTxtFx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextx0 = new javax.swing.JTextField();
        jTextx1 = new javax.swing.JTextField();
        jText2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonsalir = new javax.swing.JButton();

        jTextx2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextx2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextx2ActionPerformed(evt);
            }
        });

        jTextx3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextx3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("CALCULAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jText3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MüLLER");

        jprincipal.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("METODO DE MÜLLER");
        jLabel1.setOpaque(true);

        JFUNCION.setBackground(new java.awt.Color(102, 255, 255));
        JFUNCION.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JFUNCION.setText("FUNCIÓN:");
        JFUNCION.setOpaque(true);

        jTxtFx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFxActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X0");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X2");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X1");
        jLabel4.setOpaque(true);

        jTextx0.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextx0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextx0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextx0ActionPerformed(evt);
            }
        });

        jTextx1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextx1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jText2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("CALCULAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Variable", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonsalir.setBackground(new java.awt.Color(0, 255, 255));
        jButtonsalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonsalir.setText("SALIR");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jprincipalLayout = new javax.swing.GroupLayout(jprincipal);
        jprincipal.setLayout(jprincipalLayout);
        jprincipalLayout.setHorizontalGroup(
            jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(jprincipalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jprincipalLayout.createSequentialGroup()
                        .addComponent(JFUNCION, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jprincipalLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jprincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtFx, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jprincipalLayout.createSequentialGroup()
                            .addComponent(jTextx0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextx1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jText2))
                        .addGroup(jprincipalLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jprincipalLayout.setVerticalGroup(
            jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jprincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtFx, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(JFUNCION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextx0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextx1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jprincipalLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalLayout.createSequentialGroup()
                        .addComponent(jButtonsalir)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(66, 66, 66))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFxActionPerformed

    private void jTextx0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextx0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextx0ActionPerformed

    private void jText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText2ActionPerformed

    private void jTextx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextx2ActionPerformed

    private void jText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


    }//GEN-LAST:event_jButton2ActionPerformed
    private Double evalFunction(Double variable) {
        String fx = jTxtFx.getText();
        final Point var = new Point("x", variable);
        ParserResult result = Parser.eval(fx, var);
        //System.out.println("eval de " + variable + " " + result.getValue());
        return result.getValue();
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Double x0 = (Double.parseDouble(jTextx0.getText()));
        Double x1 = (Double.parseDouble(jTextx1.getText()));
        Double x2 = (Double.parseDouble(jText2.getText()));

        Double x3 = new Double(9);
        int itera = 0;
        double[] ejeX = new double[5];
        double[] ejeY = new double[5];

        Double h0 = new Double(9), h1 = new Double(9), d0 = new Double(9), d1 = new Double(9), A = new Double(9), B = new Double(9), C = new Double(9);

        Double den = new Double(9), raizp = new Double(9), raizn = new Double(9);
        Object[] row = new Object[2];
        do {

            DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
            //System.out.println("itera" + itera);
            row[0] = "Iteracion";
            row[1] = itera;
            tabla.addRow(row);
            h0 = x1 - x0;
            //System.out.println("h0" + h0);
            row[0] = "h0";
            row[1] = h0;
            tabla.addRow(row);
            h1 = x2 - x1;
            //System.out.println("h1" + h1);
            row[0] = "h1";
            row[1] = h1;
            tabla.addRow(row);
            d0 = (evalFunction(x1) - evalFunction(x0)) / h0;
            //System.out.println("d0" + d0);
            row[0] = "d0";
            row[1] = d0;
            tabla.addRow(row);
            d1 = (evalFunction(x2) - evalFunction(x1)) / h1;
            //System.out.println("d1" + d1);
            row[0] = "d1";
            row[1] = d1;
            tabla.addRow(row);
            A = (d1 - d0) / (h1 + h0);
            //System.out.println("A" + A);
            row[0] = "A";
            row[1] = A;
            tabla.addRow(row);
            B = (A * h1) + d1;
            //System.out.println("B" + B);
            row[0] = "B";
            row[1] = B;
            tabla.addRow(row);
            C = evalFunction(x2);
            //System.out.println("C" + C);
            row[0] = "C";
            row[1] = C;
            tabla.addRow(row);

            //raiz = Math.sqrt(B * B - 4.0 * A * C);
            raizp = B + (Math.sqrt(Math.pow(B, 2) - (4 * A * C)));
            row[0] = "raiz positiva";
            row[1] = raizp;
            tabla.addRow(row);
            raizn = B + (Math.sqrt(Math.pow(B, 2) - (4 * A * C)));
            row[0] = "raiz negativa";
            row[1] = raizn;
            tabla.addRow(row);
            //System.out.println("raizp" + raizp);
            //System.out.println("raizn" + raizn);
            /*if (Math.abs(B + raiz) > Math.abs(B - raiz)) {
                den = B + raiz;
                //System.out.println("den"+den);
            } else {
                den = B - raiz;
                //System.out.println("den"+den);
            }*/

            x3 = x2 - 2 * C / raizp;
            //System.out.println("x3" + x3);
            row[0] = "x3";
            row[1] = x3;
            tabla.addRow(row);
            //System.out.println(" x = " + x3 + " " + evalFunction(x3));

            x0 = x1;

            x1 = x2;

            x2 = x3;

            ejeX[itera] = itera + 1;
            System.out.println(itera);
            System.out.println("X:"+ejeX[itera]);
            ejeY[itera] = x3;
            System.out.println("Y:"+ejeY[itera]);
            itera++;

        } while (Math.abs(evalFunction(x3)) > 0.000001 && itera < 5);

        //evalFunction.addLinePlot("iteraciones", ejeX, ejeY);

        //evalFunction.setVisible(true);
        
        
       // XYChart diagrama=QuickChart.getChart("Miuller", "X", "F(X)", jTxtFx.getText(), ejeX, ejeY);
       
       double[] ejeXFinal = new double[itera];
       double[] ejeYFinal = new double[itera];
       for(int i=0; i<itera;i++){
           ejeXFinal[i]= ejeX[i];
           ejeYFinal[i]= ejeY[i];
       }
       XYChart diagrama=QuickChart.getChart("Miuller", "X", "F(X)", jTxtFx.getText(), ejeXFinal, ejeYFinal);
       /*final XYChart diagrama = new XYChartBuilder().width(600).height(400).title("Muller - " + jTxtFx.getText()).xAxisTitle("X").yAxisTitle("Y").build();
       diagrama.getStyler().setLegendPosition(Styler.LegendPosition.InsideNE);
       diagrama.getStyler().setDefaultSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Line);
       diagrama.addSeries(".", ejeXFinal, ejeYFinal);*/
        
        //new SwingWrapper(diagrama).displayChart();
        try {
            //new SwingWrapper(diagrama).displayChart();
            BitmapEncoder.saveBitmap(diagrama, "./Mueller", BitmapFormat.BMP);
            
            
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    JFrame frame = new JFrame("Grafica");
                    frame.setLayout(new BorderLayout());
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    
                    JPanel chartPanel = new XChartPanel<XYChart>(diagrama);
                    frame.add(chartPanel, BorderLayout.CENTER);
                    
                    JLabel Label=new JLabel("diagrama",SwingConstants.CENTER);
                    frame.add(Label,BorderLayout.SOUTH);
                    frame.pack();
                    frame.setVisible(true);
                            
                }
            });
            
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(müller_Meto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(müller_Meto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(müller_Meto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(müller_Meto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(müller_Meto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new müller_Meto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JFUNCION;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText2;
    private javax.swing.JTextField jText3;
    private javax.swing.JTextField jTextx0;
    private javax.swing.JTextField jTextx1;
    private javax.swing.JTextField jTextx2;
    private javax.swing.JTextField jTextx3;
    private javax.swing.JTextField jTxtFx;
    private javax.swing.JPanel jprincipal;
    // End of variables declaration//GEN-END:variables
}
